from __future__ import annotations

import json
from pathlib import Path


def transcribe_stub(input_path: str, run_dir: str) -> Path:
    source = Path(input_path)
    target_dir = Path(run_dir)

    if not source.is_file():
        raise FileNotFoundError(f"input file does not exist: {source}")
    if not target_dir.is_dir():
        raise FileNotFoundError(f"run directory does not exist: {target_dir}")

    transcript = {
        "schema_version": "transcript.v1",
        "source": {
            "input_path": str(source),
            "mode": "stub",
        },
        "language": "unknown",
        "duration_seconds": None,
        "segments": [
            {
                "id": "seg_0001",
                "start": 0.0,
                "end": 2.0,
                "text": "Stub transcript generated by BYOM Video.",
            }
        ],
    }

    output_path = target_dir / "transcript.json"
    output_path.write_text(json.dumps(transcript, indent=2) + "\n", encoding="utf-8")
    return output_path
