package exportscript

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Summary struct {
	ArtifactPath string
	CommandCount int
	Mode         string
}

type clip struct {
	ID             string  `json:"id"`
	Start          float64 `json:"start"`
	End            float64 `json:"end"`
	OutputFilename string  `json:"output_filename,omitempty"`
}

func WriteFFmpegScript(sourcePath string, outputPath string, inputPath string, format string, mode string) (Summary, error) {
	if format != "mp4" {
		return Summary{}, fmt.Errorf("unsupported ffmpeg output format %q; supported values: mp4", format)
	}
	if mode == "" {
		mode = "stream-copy"
	}
	if mode != "stream-copy" && mode != "reencode" {
		return Summary{}, fmt.Errorf("unsupported ffmpeg mode %q; supported values: stream-copy, reencode", mode)
	}
	data, err := os.ReadFile(sourcePath)
	if err != nil {
		return Summary{}, fmt.Errorf("read ffmpeg source: %w", err)
	}
	var source struct {
		Clips []clip `json:"clips"`
	}
	if err := json.Unmarshal(data, &source); err != nil {
		return Summary{}, fmt.Errorf("decode ffmpeg source: %w", err)
	}

	var builder strings.Builder
	builder.WriteString("#!/usr/bin/env bash\n")
	builder.WriteString("set -euo pipefail\n\n")
	builder.WriteString("# Generated by BYOM Video. Inspect before running.\n")
	fmt.Fprintf(&builder, "# mode: %s\n", mode)
	if mode == "stream-copy" {
		builder.WriteString("# Stream-copy cuts are fast but may not be frame-perfect.\n")
		builder.WriteString("# For frame-accurate cuts, use reencode mode.\n\n")
	} else {
		builder.WriteString("# Re-encode mode is slower but more frame-accurate.\n\n")
	}
	builder.WriteString("mkdir -p exports\n\n")
	for _, clip := range source.Clips {
		output := clip.OutputFilename
		if output == "" {
			output = fmt.Sprintf("%s.%s", clip.ID, format)
		}
		if !strings.Contains(output, "/") {
			output = filepath.ToSlash(filepath.Join("exports", output))
		}
		fmt.Fprintf(&builder, "# %s\n", clip.ID)
		if mode == "stream-copy" {
			fmt.Fprintf(&builder, "ffmpeg -y -ss %.3f -to %.3f -i %s -c copy %s\n", clip.Start, clip.End, ShellQuote(inputPath), ShellQuote(output))
			fmt.Fprintf(&builder, "# ffmpeg -y -ss %.3f -to %.3f -i %s -c:v libx264 -c:a aac %s\n\n", clip.Start, clip.End, ShellQuote(inputPath), ShellQuote(output))
		} else {
			fmt.Fprintf(&builder, "ffmpeg -y -ss %.3f -to %.3f -i %s -c:v libx264 -c:a aac %s\n\n", clip.Start, clip.End, ShellQuote(inputPath), ShellQuote(output))
		}
	}
	if err := os.WriteFile(outputPath, []byte(builder.String()), 0o755); err != nil {
		return Summary{}, fmt.Errorf("write ffmpeg script: %w", err)
	}
	return Summary{ArtifactPath: "ffmpeg_commands.sh", CommandCount: len(source.Clips), Mode: mode}, nil
}

func ShellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
