#!/usr/bin/env bash
set -euo pipefail

# Generated by BYOM Video. Inspect before running.
# mode: reencode
# Re-encode mode is slower but more frame-accurate.

mkdir -p exports

# clip_0001
ffmpeg -y -ss 0.000 -to 4.480 -i '/Users/mireliftikharahmed/Documents/BYOMVIDEO/media/Untitled.mov' -c:v libx264 -c:a aac 'exports/clip_0001.mp4'

