#!/usr/bin/env bash
set -euo pipefail

# Generated by BYOM Video. Inspect before running.
# Stream-copy cuts are fast but may not be frame-perfect.
# For frame-accurate cuts, use the commented re-encode template below each command.

mkdir -p exports

# clip_0001
ffmpeg -y -ss 0.000 -to 4.480 -i '/Users/mireliftikharahmed/Documents/BYOMVIDEO/media/Untitled.mov' -c copy 'exports/clip_0001.mp4'
# ffmpeg -y -ss 0.000 -to 4.480 -i '/Users/mireliftikharahmed/Documents/BYOMVIDEO/media/Untitled.mov' -c:v libx264 -c:a aac 'exports/clip_0001.mp4'

